=== andiyudistira/Pandawa/Data/PlacesSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="BaliProvinces">
       <xs:complexType>
          <xs:sequence>          	
          	<xs:element name="Areas" type="Area" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="News" type="News" minOccurs="0" maxOccurs="unbounded"/>             
          </xs:sequence>
       </xs:complexType>
    </xs:element>
   <xs:complexType name="Area">
      <xs:sequence>
         <xs:element name="AreaId" type="xs:integer"></xs:element>
         <xs:element name="AreaCode" type="xs:string"></xs:element>
         <xs:element name="Description" type="xs:string"></xs:element>
         <xs:element name="Places" type="Place" minOccurs="1" maxOccurs="unbounded"></xs:element>
         <xs:element name="InsertBy" type="xs:string"></xs:element>
         <xs:element name="InsertDate" type="xs:dateTime"></xs:element>
         <xs:element name="UpdateBy" type="xs:string"></xs:element>
         <xs:element name="UpdateDate" type="xs:dateTime"></xs:element>
         <xs:element name="RecordStatus" type="xs:boolean"></xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Place">
      <xs:sequence>
         <xs:element name="PlaceId" type="xs:integer"></xs:element>
         <xs:element name="PlaceCode" type="xs:string"></xs:element>
         <xs:element name="Name" type="xs:string"></xs:element>
         <xs:element name="Position" type="xs:string"></xs:element>
         <xs:element name="Address" type="xs:string"></xs:element>
         <xs:element name="Category" type="xs:string"></xs:element>
         <xs:element name="Contents" type="PlaceContent" minOccurs="1" maxOccurs="unbounded"></xs:element>
         <xs:element name="Description" type="xs:string"></xs:element>
         <xs:element name="InsertBy" type="xs:string"></xs:element>
         <xs:element name="InsertDate" type="xs:dateTime"></xs:element>
         <xs:element name="UpdateBy" type="xs:string"></xs:element>
         <xs:element name="UpdateDate" type="xs:dateTime"></xs:element>
         <xs:element name="RecordStatus" type="xs:boolean"></xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="News">
      <xs:sequence>
         <xs:element name="NewsId" type="xs:integer"></xs:element>
         <xs:element name="NewsCode" type="xs:string"></xs:element>
         <xs:element name="Title" type="xs:string"></xs:element>
         <xs:element name="DateSubmited" type="xs:dateTime"></xs:element>
         <xs:element name="Content" type="xs:string"></xs:element>
         <xs:element name="Tag" type="xs:string"></xs:element>
         <xs:element name="Photos" type="Photo" minOccurs="1" maxOccurs="unbounded"></xs:element>
         <xs:element name="InsertBy" type="xs:string"></xs:element>
         <xs:element name="InsertDate" type="xs:dateTime"></xs:element>
         <xs:element name="UpdateBy" type="xs:string"></xs:element>
         <xs:element name="UpdateDate" type="xs:dateTime"></xs:element>
         <xs:element name="RecordStatus" type="xs:boolean"></xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Photo">
      <xs:sequence>
         <xs:element name="PhotoId" type="xs:integer"></xs:element>
         <xs:element name="PhotoCode" type="xs:string"></xs:element>
         <xs:element name="DateTaken" type="xs:dateTime"></xs:element>
         <xs:element name="DateSubmited" type="xs:dateTime"></xs:element>
         <xs:element name="Description" type="xs:string"></xs:element>
         <xs:element name="Comment" type="xs:string"></xs:element>
         <xs:element name="InsertBy" type="xs:string"></xs:element>
         <xs:element name="InsertDate" type="xs:dateTime"></xs:element>
         <xs:element name="UpdateBy" type="xs:string"></xs:element>
         <xs:element name="UpdateDate" type="xs:dateTime"></xs:element>
         <xs:element name="RecordStatus" type="xs:boolean"></xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="PlaceContent">
      <xs:sequence>
         <xs:element name="PlaceContentId" type="xs:integer"></xs:element>
         <xs:element name="PlaceContentCode" type="xs:string"></xs:element>
         <xs:element name="Name" type="xs:string"></xs:element>
         <xs:element name="Description" type="xs:string"></xs:element>
         <xs:element name="Photos" type="Photo" minOccurs="1" maxOccurs="unbounded"></xs:element>
         <xs:element name="Comment" type="xs:string"></xs:element>
         <xs:element name="InsertBy" type="xs:string"></xs:element>
         <xs:element name="InsertDate" type="xs:dateTime"></xs:element>
         <xs:element name="UpdateBy" type="xs:string"></xs:element>
         <xs:element name="UpdateDate" type="xs:dateTime"></xs:element>
         <xs:element name="RecordStatus" type="xs:boolean"></xs:element>
      </xs:sequence>
   </xs:complexType>
</xs:schema>

=== andiyudistira/Pandawa/Data/PlacesData.xml
<?xml version="1.0" encoding="utf-8"?>
<BaliProvinces xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PlacesSchema.xsd">
   <Areas>
      <AreaCode>001</AreaCode>
      <Description>Test Dulu</Description>
      <Places>
         <PlaceCode>1</PlaceCode>
         <Name>Test Lagi</Name>
         <Position>www</Position>
         <Address>sdfsf</Address>
         <Category>dfsdfs</Category>
         <Contents>
            <PlaceContentCode>223</PlaceContentCode>
            <Name>asda</Name>
            <Description>sdfsfdgdf</Description>
            <Photos>
               <PhotoCode>12</PhotoCode>
               <DateTaken>123</DateTaken>
               <DateSubmited>lfgme</DateSubmited>
               <Description>sfsdfdf</Description>
               <Comment>sdfsf</Comment>               
            </Photos>
            <Comment>sdfsnfhnos</Comment>
         </Contents>
         <Contents>
            <PlaceContentCode>224</PlaceContentCode>
            <Name>asda</Name>
            <Description>sdfsfdgdf</Description>
            <Photos>
               <PhotoCode>12</PhotoCode>
               <DateTaken>123</DateTaken>
               <DateSubmited>lfgme</DateSubmited>
               <Description>sfsdfdf</Description>
               <Comment>sdfsf</Comment>
            </Photos>
            <Comment>sdfsnfhnos</Comment>
         </Contents>
         <Description>asdsadsa</Description>
      </Places>
      <Places>
         <PlaceCode>2</PlaceCode>
         <Name>Test Lagi 2</Name>
         <Position>www 2</Position>
         <Address>sdfsf 2</Address>
         <Category>dfsdfs 2</Category>
         <Contents>
            <PlaceContentCode>229</PlaceContentCode>
            <Name>asda</Name>
            <Description>sdfsfdgdf</Description>
            <Photos>
               <PhotoCode>12</PhotoCode>
               <DateTaken>123</DateTaken>
               <DateSubmited>lfgme</DateSubmited>
               <Description>sfsdfdf</Description>
               <Comment>sdfsf</Comment>
            </Photos>
            <Comment>sdfsnfhnos</Comment>
         </Contents>
         <Contents>
            <PlaceContentCode>228</PlaceContentCode>
            <Name>asda</Name>
            <Description>sdfsfdgdf</Description>
            <Photos>
               <PhotoCode>12</PhotoCode>
               <DateTaken>123</DateTaken>
               <DateSubmited>lfgme</DateSubmited>
               <Description>sfsdfdf</Description>
               <Comment>sdfsf</Comment>
            </Photos>
            <Comment>sdfsnfhnos</Comment>
         </Contents>
         <Description>asdsadsa</Description>
      </Places>
   </Areas>
   <Areas>
      <AreaCode>002</AreaCode>
      <Description>Test Bujur</Description>
      <Places>
         <PlaceCode>1</PlaceCode>
         <Name>Test Lagi</Name>
         <Position>www</Position>
         <Address>sdfsf</Address>
         <Category>dfsdfs</Category>
         <Contents>
            <PlaceContentCode>223</PlaceContentCode>
            <Name>asda</Name>
            <Description>sdfsfdgdf</Description>
            <Photos>
               <PhotoCode>12</PhotoCode>
               <DateTaken>123</DateTaken>
               <DateSubmited>lfgme</DateSubmited>
               <Description>sfsdfdf</Description>
               <Comment>sdfsf</Comment>
            </Photos>
            <Comment>sdfsnfhnos</Comment>
         </Contents>
         <Contents>
            <PlaceContentCode>224</PlaceContentCode>
            <Name>asda</Name>
            <Description>sdfsfdgdf</Description>
            <Photos>
               <PhotoCode>12</PhotoCode>
               <DateTaken>123</DateTaken>
               <DateSubmited>lfgme</DateSubmited>
               <Description>sfsdfdf</Description>
               <Comment>sdfsf</Comment>
            </Photos>
            <Comment>sdfsnfhnos</Comment>
         </Contents>
         <Description>asdsadsa</Description>
      </Places>
      <Places>
         <PlaceCode>2</PlaceCode>
         <Name>Test Lagi 2</Name>
         <Position>www 2</Position>
         <Address>sdfsf 2</Address>
         <Category>dfsdfs 2</Category>
         <Contents>
            <PlaceContentCode>229</PlaceContentCode>
            <Name>asda</Name>
            <Description>sdfsfdgdf</Description>
            <Photos>
               <PhotoCode>12</PhotoCode>
               <DateTaken>123</DateTaken>
               <DateSubmited>lfgme</DateSubmited>
               <Description>sfsdfdf</Description>
               <Comment>sdfsf</Comment>
            </Photos>
            <Comment>sdfsnfhnos</Comment>
         </Contents>
         <Contents>
            <PlaceContentCode>228</PlaceContentCode>
            <Name>asda</Name>
            <Description>sdfsfdgdf</Description>
            <Photos>
               <PhotoCode>12</PhotoCode>
               <DateTaken>123</DateTaken>
               <DateSubmited>lfgme</DateSubmited>
               <Description>sfsdfdf</Description>
               <Comment>sdfsf</Comment>
            </Photos>
            <Comment>sdfsnfhnos</Comment>
         </Contents>
         <Description>asdsadsa</Description>
      </Places>
   </Areas>
   <News>
      <NewsCode>12345</NewsCode>
      <Title>Gak ada</Title>
      <DateSubmited>sdfsdf</DateSubmited>
      <Content>sdljfvbibiwsefisewfow</Content>
      <Tag>none</Tag>
      <Photos>
         <PhotoCode>123</PhotoCode>
         <DateTaken>sfn</DateTaken>
         <DateSubmited>dfnsdo</DateSubmited>
         <Description>My My</Description>
         <Comment>oldhnfo</Comment>
      </Photos>
      <Photos>
         <PhotoCode>124</PhotoCode>
         <DateTaken>sfn</DateTaken>
         <DateSubmited>dfnsdo</DateSubmited>
         <Description>My My</Description>
         <Comment>oldhnfo</Comment>
      </Photos>
      <Photos>
         <PhotoCode>125</PhotoCode>
         <DateTaken>sfn</DateTaken>
         <DateSubmited>dfnsdo</DateSubmited>
         <Description>My My</Description>
         <Comment>oldhnfo</Comment>
      </Photos>
   </News>
</BaliProvinces>
